#!/usr/bin/python3
import xml.etree.ElementTree

def list2c(element):
  if element.tag[-5:] == "_list":
    c = open("src/auto/" + element.tag + ".c", 'w')
    h = open("src/auto/" + element.tag + ".h", 'w')
    warning = "/* DO NOT EDIT - this file is autogenerated from XML (" + element.tag + ") */\n"
    c.write(warning)
    h.write(warning)
    name = element.tag[0:-5]
    cname_base = element.tag[0:-4].upper()
    
    # TODO do something generic when (if) needed
    for d in element.findall(name):
      rom = d.attrib['rom']
      c.write("{ ")
      for i in range(0,len(rom),2):
        c.write("0x" + rom[i:i+2] + ", ")
      c.write("},\n")

      h.write(cname_base + d.attrib['cname'] + ',\n')

    h.write(cname_base + 'NR\n')

  else:
    raise Exception("Not a parsable element")


def gen_c():
  for el in xml.etree.ElementTree.parse("xml/xml.xml").getiterator():
    if el.tag[-5:] == "_list":
      list2c(el)


if __name__ == "__main__":
  import sys
  if len(sys.argv) > 1:
    for el in xml.etree.ElementTree.parse(sys.argv[1]).getiterator():
      print(el)
